version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.2.0

executors:
  docker-publisher:
    docker:
      - image: cimg/node:16.13.1-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

  python-linter:
    docker:
      - image: circleci/python:latest

jobs:
    test:
      executor: python-linter
      steps:
      - checkout
    build_and_publish:
      executor: docker-publisher
      steps:
        - checkout
    deploy:
      executor: gcp-cli/default
      steps:
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: deploy service
          command: |
            gcloud --quiet compute ssh  "$GCE_INSTANCE_NAME" --tunnel-through-iap --command="docker pull google/cloud-sdk:latest"
workflows:
  version: 2
  test-build-deploy:
    jobs:
       - test
       - build_and_publish:
          requires:
            - test
       - deploy:
          requires:
            - build_and_publish

